#自动配置文件找到自动配置的信息,必须被@Configuration标记,当做一个Bean来处理
#org.smileframework.autoconfigure.EnableAutoConfiguration:
#  - org.smileframework.autoconfigure.DubbozAutoConfiguration

# 初始化前后处理器,必须被@BeanProcessor标记,当做一个Bean来处理
#org.smileframework.beans.postprocessor.annotation.BeanProcessor:
#  - org.smileframework.aop.postprocessor.SimpleAopProxyPostProcesstor
# BeanFactory处理器,必须被@BeanFactoryProcessor标记,当做一个Bean来处理
#org.smileframework.beans.postprocessor.annotation.BeanFactoryProcessor:
#  - org.smileframework.beans.beanfactory.condition.postprocessor.PreConditionBeanFactoryPostProcessor
# 自定义的BeanDefinition解析器
org.hanframework.autoconfigure.EnableAutoConfiguration:
  - org.hanframework.web.configuration.AutoWebConfiguration